name: Build

on:
  push:
    tags: ['*']
  pull_request:
    branches: [main]

jobs:

  build-py:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Test
      run: python -m unittest discover -p '*._tests.py'
